version: "2"

services:

  web:
    build: .
    # image: ctftraining/ddctf_2019_homebrew_event_loop
    restart: always
    ports:
      - "8085:80"
    environment:
      - FLAG=flag{3v41_3v3nt_100p_aNd_fLASK_c0Ok1e}